### ISSUE TITLE
[NEW]

### ISSUE THREAD

**Issue by Denisbg2011game** [TheBobPony/getwindows11.tech#67]
# Important

Before requesting to have a mirror added, be sure you view our [contribution][contributing] guidelines.

**URL**
http://91.148.147.117/21996.1.210529-1541.co_release_CLIENT_CONSUMER_x64FRE_en-us.iso

**Type**
Normal URL

**Notes**
Its hosted on my pc so its not gonna be online all the time but most of the time it is going to be online.

[contributing]: https://github.com/thebobpony/getwindows11.tech/blob/main/.github/CONTRIBUTING.md "CONTRIBUTING GUIDELINES"

**Comment by sysdotini** [comment]
We only add mirrors that are hosted on a permanent, preferably a non-residential host.

**Comment by Denisbg2011game** [comment]
> We only add mirrors that are hosted on a permanent, preferably a non-residential host.


Do I need to make Pergament https host I can but the people hosting it can easily take it down but the one on my PC can't be taken down as it isn't a cloud fare etc hosting

**Comment by PolishNeko** [comment]
> > We only add mirrors that are hosted on a permanent, preferably a non-residential host.
> 
> Do I need to make Pergament https host I can but the people hosting it can easily take it down but the one on my PC can't be taken down as it isn't a cloud fare etc hosting

Apparently your IP points to a Bulgarian LIR service and it says you are in a datacenter for me, and if you can do the "Pergament https host" then go ahead, Cloudflare only **caches** and you manage the DNS from there, after all if someone at Microsoft goes nuclear and send a DMCA notice, well you receive the scary warning from Cloudflare and your provider doesnt care at all or otherwise they will piss on you, also what do you mean of "the people hosting it", we are clearly hosting the ISO and no one is going to try and take down

**Comment by Denisbg2011game** [comment]
Ok when I am home I will try to host on https site and not self hosting
